### ISSUE TITLE
caj2pdf：未找到命令

### ISSUE THREAD

**Issue by RussellGee** [zombie110year/caj2pdf-restructured#1]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/caj2pdf/discussion/issues)进行讨论。

1) 正在使用最新版本的CAJ2PDF

2) 在ubuntu16.04系统将xxx.caj转换为xxx.pdf。convert
已经按照安装说明进行安装：
运行命令:
`
sudo LIBJBIG2DEC=1 pip install caj2pdf-restructured
`
出现如下输出：
`
WARNING: The directory '/home/smart/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/smart/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: caj2pdf-restructured in /usr/local/python3/lib/python3.8/site-packages (0.1.0a1)
Requirement already satisfied: pypdf2<2.0.0,>=1.26.0 in /usr/local/python3/lib/python3.8/site-packages (from caj2pdf-restructured) (1.26.0)
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`
3) 你看到的不正常的现象是什么？（请描述具体现象，比如PDF打不开等）
在终端运行命令：
`
caj2pdf convert xxx.caj   -o xxx.pdf
`
终端出现如下输出：
`
caj2pdf：未找到命令
`
4) 你期待看到的正确表现是怎样的？
能够在终端运行如下命令：
`
caj2pdf convert xxx.caj   -o xxx.pdf
`
并正常成功转换为pdf文件
5) 请附上你的配置（Python版本、Python包版本以及mutools版本）。
python版本：3.8.1；mutools 为在 https://mupdf.com/downloads/ 下载1.18版本，并按照README安装
6)  请附上出错时软件输出的错误信息。
在终端运行命令：
`
caj2pdf convert xxx.caj   -o xxx.pdf
`
终端出现如下输出：
`
caj2pdf：未找到命令
`

**Comment by zombie110year** [comment]
# 建议按照以下步骤尝试解决问题

我只在 ArchLinux 做过测试，貌似 apt 上的包名和 pacman 的不太一样。

1. 在虚拟环境中进行安装：使用 `python -m venv caj_venv` 创建名为 `caj_venv` 的虚拟环境目录，并使用 `source caj_venv/bin/activate` 命令激活
1. 安装开发包 `sudo apt install libjbig2dec0-dev`
1. 使用 `pkg-config --libs --cflags jbig2dec` 查询 jbig2dec 是否被正确识别
1. 在虚拟环境中使用 `LIBJBIG2DEC=1 pip install caj2pdf-restructured -vv` 安装并查看详细的输出，观察是否安装成功

# poppler 可用

在 Debian 系系统上安装 jbig2dec 依赖库似乎有点麻烦，建议先使用 libpoppler 编译。Debian/Ubuntu 安装依赖应当使用以下命令：

```sh
sudo apt install build-essential libpoppler-dev mupdf-tools
pip install caj2pdf-restructured
```

之后我会在 Ubuntu 虚拟机下进行测试，并发布修改后的版本。

**Comment by zombie110year** [comment]
根据我的测试，Ubuntu 16.04 可能无法编译此项目，有几个需要注意的点：

1. `libpoppler-dev` 未提供头文件，需要额外安装 `libpoppler-private-dev` 包才有头文件
2. 安装后发现 poppler 版本不对，无法匹配输入 `enum ObjType` 的构造函数。较新版本已达到 0.86.1-0ubuntu1 ，而 Ubuntu 16.04 仓库中的仅为 0.41.0-0ubuntu1.16.

因此，建议采用以下方案之一：

+ 升级 Ubuntu 版本，最好到最新的 Ubuntu 21.04
+ 换用 Arch Linux
+ 克隆该仓库，修改编译脚本，手动安装并编译最新版本的依赖，手动编译并安装 caj2pdf

**Comment by RussellGee** [comment]
> 根据我的测试，Ubuntu 16.04 可能无法编译此项目，有几个需要注意的点：
> 
>     1. `libpoppler-dev` 未提供头文件，需要额外安装 `libpoppler-private-dev` 包才有头文件
> 
>     2. 安装后发现 poppler 版本不对，无法匹配输入 `enum ObjType` 的构造函数。较新版本已达到 0.86.1-0ubuntu1 ，而 Ubuntu 16.04 仓库中的仅为 0.41.0-0ubuntu1.16.
> 
> 
> 因此，建议采用以下方案之一：
> 
>     * 升级 Ubuntu 版本，最好到最新的 Ubuntu 21.04
> 
>     * 换用 Arch Linux
> 
>     * 克隆该仓库，修改编译脚本，手动安装并编译最新版本的依赖，手动编译并安装 caj2pdf

谢谢，我试一下，有结果了及时给你回复。

**Comment by RussellGee** [comment]
> 根据我的测试，Ubuntu 16.04 可能无法编译此项目，有几个需要注意的点：
> 
>     1. `libpoppler-dev` 未提供头文件，需要额外安装 `libpoppler-private-dev` 包才有头文件
> 
>     2. 安装后发现 poppler 版本不对，无法匹配输入 `enum ObjType` 的构造函数。较新版本已达到 0.86.1-0ubuntu1 ，而 Ubuntu 16.04 仓库中的仅为 0.41.0-0ubuntu1.16.
> 
> 
> 因此，建议采用以下方案之一：
> 
>     * 升级 Ubuntu 版本，最好到最新的 Ubuntu 21.04
> 
>     * 换用 Arch Linux
> 
>     * 克隆该仓库，修改编译脚本，手动安装并编译最新版本的依赖，手动编译并安装 caj2pdf

谢谢，我试一下。
